CODES = {
    'AED': 'UAE Dirham',
    'AFN': 'Afghan Afghani',
    'ALL': 'Albanian Lek',
    'AMD': 'Armenian Dram',
    'ANG': 'Netherlands Antillian Guilder',
    'AOA': 'Angolan Kwanza',
    'ARS': 'Argentine Peso',
    'AUD': 'Australian Dollar',
    'AWG': 'Aruban Florin',
    'AZN': 'Azerbaijani Manat',
    'BAM': 'Bosnia and Herzegovina Convertible Mark',
    'BBD': 'Barbados Dollar',
    'BDT': 'Bangladeshi Taka',
    'BGN': 'Bulgarian Lev',
    'BHD': 'Bahraini Dinar',
    'BIF': 'Burundian Franc',
    'BMD': 'Bermudian Dollar',
    'BND': 'Brunei Dollar',
    'BOB': 'Bolivian Boliviano',
    'BRL': 'Brazilian Real',
    'BSD': 'Bahamian Dollar',
    'BTN': 'Bhutanese Ngultrum',
    'BWP': 'Botswana Pula',
    'BYN': 'Belarusian Ruble',
    'BZD': 'Belize Dollar',
    'CAD': 'Canadian Dollar',
    'CDF': 'Congolese Franc',
    'CHF': 'Swiss Franc',
    'CLP': 'Chilean Peso',
    'CNY': 'Chinese Renminbi',
    'COP': 'Colombian Peso',
    'CRC': 'Costa Rican Colon',
    'CUC': 'Cuban Convertible Peso',
    'CUP': 'Cuban Peso',
    'CVE': 'Cape Verdean Escudo',
    'CZK': 'Czech Koruna',
    'DJF': 'Djiboutian Franc',
    'DKK': 'Danish Krone',
    'DOP': 'Dominican Peso',
    'DZD': 'Algerian Dinar',
    'EGP': 'Egyptian Pound',
    'ERN': 'Eritrean Nakfa',
    'ETB': 'Ethiopian Birr',
    'EUR': 'Euro',
    'FJD': 'Fiji Dollar',
    'FKP': 'Falkland Islands Pound',
    'FOK': 'Faroese Króna',
    'GBP': 'Pound Sterling',
    'GEL': 'Georgian Lari',
    'GGP': 'Guernsey Pound',
    'GHS': 'Ghanaian Cedi',
    'GIP': 'Gibraltar Pound',
    'GMD': 'Gambian Dalasi',
    'GNF': 'Guinean Franc',
    'GTQ': 'Guatemalan Quetzal',
    'GYD': 'Guyanese Dollar',
    'HKD': 'Hong Kong Dollar',
    'HNL': 'Honduran Lempira',
    'HRK': 'Croatian Kuna',
    'HTG': 'Haitian Gourde',
    'HUF': 'Hungarian Forint',
    'IDR': 'Indonesian Rupiah',
    'ILS': 'Israeli New Shekel',
    'IMP': 'Manx Pound',
    'INR': 'Indian Rupee',
    'IQD': 'Iraqi Dinar',
    'IRR': 'Iranian Rial',
    'ISK': 'Icelandic Króna',
    'JMD': 'Jamaican Dollar',
    'JOD': 'Jordanian Dinar',
    'JPY': 'Japanese Yen',
    'KES': 'Kenyan Shilling',
    'KGS': 'Kyrgyzstani Som',
    'KHR': 'Cambodian Riel',
    'KID': 'Kiribati Dollar',
    'KMF': 'Comorian Franc',
    'KRW': 'South Korean Won',
    'KWD': 'Kuwaiti Dinar',
    'KYD': 'Cayman Islands Dollar',
    'KZT': 'Kazakhstani Tenge',
    'LAK': 'Lao Kip',
    'LBP': 'Lebanese Pound',
    'LKR': 'Sri Lanka Rupee',
    'LRD': 'Liberian Dollar',
    'LSL': 'Lesotho Loti',
    'LYD': 'Libyan Dinar',
    'MAD': 'Moroccan Dirham',
    'MDL': 'Moldovan Leu',
    'MGA': 'Malagasy Ariary',
    'MKD': 'Macedonian Denar',
    'MMK': 'Burmese Kyat',
    'MNT': 'Mongolian Tögrög',
    'MOP': 'Macanese Pataca',
    'MRU': 'Mauritanian Ouguiya',
    'MUR': 'Mauritian Rupee',
    'MVR': 'Maldivian Rufiyaa',
    'MWK': 'Malawian Kwacha',
    'MXN': 'Mexican Peso',
    'MYR': 'Malaysian Ringgit',
    'MZN': 'Mozambican Metical',
    'NAD': 'Namibian Dollar',
    'NGN': 'Nigerian Naira',
    'NIO': 'Nicaraguan Córdoba',
    'NOK': 'Norwegian Krone',
    'NPR': 'Nepalese Rupee',
    'NZD': 'New Zealand Dollar',
    'OMR': 'Omani Rial',
    'PAB': 'Panamanian Balboa',
    'PEN': 'Peruvian Sol',
    'PGK': 'Papua New Guinean Kina',
    'PHP': 'Philippine Peso',
    'PKR': 'Pakistani Rupee',
    'PLN': 'Polish Złoty',
    'PYG': 'Paraguayan Guaraní',
    'QAR': 'Qatari Riyal',
    'RON': 'Romanian Leu',
    'RSD': 'Serbian Dinar',
    'RUB': 'Russian Ruble',
    'RWF': 'Rwandan Franc',
    'SAR': 'Saudi Riyal',
    'SBD': 'Solomon Islands Dollar',
    'SCR': 'Seychellois Rupee',
    'SDG': 'Sudanese Pound',
    'SEK': 'Swedish Krona',
    'SGD': 'Singapore Dollar',
    'SHP': 'Saint Helena Pound',
    'SLL': 'Sierra Leonean Leone',
    'SOS': 'Somali Shilling',
    'SRD': 'Surinamese Dollar',
    'SSP': 'South Sudanese Pound',
    'STN': 'São Tomé and Príncipe Dobra',
    'SYP': 'Syrian Pound',
    'SZL': 'Eswatini Lilangeni',
    'THB': 'Thai Baht',
    'TJS': 'Tajikistani Somoni',
    'TMT': 'Turkmenistan Manat',
    'TND': 'Tunisian Dinar',
    'TOP': 'Tongan Paʻanga',
    'TRY': 'Turkish Lira',
    'TTD': 'Trinidad and Tobago Dollar',
    'TVD': 'Tuvaluan Dollar',
    'TWD': 'New Taiwan Dollar',
    'TZS': 'Tanzanian Shilling',
    'UAH': 'Ukrainian Hryvnia',
    'UGX': 'Ugandan Shilling',
    'USD': 'United States Dollar',
    'UYU': 'Uruguayan Peso',
    'UZS': "Uzbekistani So'm",
    'VES': 'Venezuelan Bolívar Soberano',
    'VND': 'Vietnamese Đồng',
    'VUV': 'Vanuatu Vatu',
    'WST': 'Samoan Tālā',
    'XAF': 'Central African CFA Franc',
    'XCD': 'East Caribbean Dollar',
    'XDR': 'Special Drawing Rights',
    'XOF': 'West African CFA franc',
    'XPF': 'CFP Franc',
    'YER': 'Yemeni Rial',
    'ZAR': 'South African Rand',
    'ZMW': 'Zambian Kwacha'
}  # Supported Codes
REVERSE_CODES = {
    'Afghan Afghani': 'AFN',
    'Albanian Lek': 'ALL',
    'Algerian Dinar': 'DZD',
    'Angolan Kwanza': 'AOA',
    'Argentine Peso': 'ARS',
    'Armenian Dram': 'AMD',
    'Aruban Florin': 'AWG',
    'Australian Dollar': 'AUD',
    'Azerbaijani Manat': 'AZN',
    'Bahamian Dollar': 'BSD',
    'Bahraini Dinar': 'BHD',
    'Bangladeshi Taka': 'BDT',
    'Barbados Dollar': 'BBD',
    'Belarusian Ruble': 'BYN',
    'Belize Dollar': 'BZD',
    'Bermudian Dollar': 'BMD',
    'Bhutanese Ngultrum': 'BTN',
    'Bolivian Boliviano': 'BOB',
    'Bosnia and Herzegovina Convertible Mark': 'BAM',
    'Botswana Pula': 'BWP',
    'Brazilian Real': 'BRL',
    'Brunei Dollar': 'BND',
    'Bulgarian Lev': 'BGN',
    'Burmese Kyat': 'MMK',
    'Burundian Franc': 'BIF',
    'CFP Franc': 'XPF',
    'Cambodian Riel': 'KHR',
    'Canadian Dollar': 'CAD',
    'Cape Verdean Escudo': 'CVE',
    'Cayman Islands Dollar': 'KYD',
    'Central African CFA Franc': 'XAF',
    'Chilean Peso': 'CLP',
    'Chinese Renminbi': 'CNY',
    'Colombian Peso': 'COP',
    'Comorian Franc': 'KMF',
    'Congolese Franc': 'CDF',
    'Costa Rican Colon': 'CRC',
    'Croatian Kuna': 'HRK',
    'Cuban Convertible Peso': 'CUC',
    'Cuban Peso': 'CUP',
    'Czech Koruna': 'CZK',
    'Danish Krone': 'DKK',
    'Djiboutian Franc': 'DJF',
    'Dominican Peso': 'DOP',
    'East Caribbean Dollar': 'XCD',
    'Egyptian Pound': 'EGP',
    'Eritrean Nakfa': 'ERN',
    'Eswatini Lilangeni': 'SZL',
    'Ethiopian Birr': 'ETB',
    'Euro': 'EUR',
    'Falkland Islands Pound': 'FKP',
    'Faroese Króna': 'FOK',
    'Fiji Dollar': 'FJD',
    'Gambian Dalasi': 'GMD',
    'Georgian Lari': 'GEL',
    'Ghanaian Cedi': 'GHS',
    'Gibraltar Pound': 'GIP',
    'Guatemalan Quetzal': 'GTQ',
    'Guernsey Pound': 'GGP',
    'Guinean Franc': 'GNF',
    'Guyanese Dollar': 'GYD',
    'Haitian Gourde': 'HTG',
    'Honduran Lempira': 'HNL',
    'Hong Kong Dollar': 'HKD',
    'Hungarian Forint': 'HUF',
    'Icelandic Króna': 'ISK',
    'Indian Rupee': 'INR',
    'Indonesian Rupiah': 'IDR',
    'Iranian Rial': 'IRR',
    'Iraqi Dinar': 'IQD',
    'Israeli New Shekel': 'ILS',
    'Jamaican Dollar': 'JMD',
    'Japanese Yen': 'JPY',
    'Jordanian Dinar': 'JOD',
    'Kazakhstani Tenge': 'KZT',
    'Kenyan Shilling': 'KES',
    'Kiribati Dollar': 'KID',
    'Kuwaiti Dinar': 'KWD',
    'Kyrgyzstani Som': 'KGS',
    'Lao Kip': 'LAK',
    'Lebanese Pound': 'LBP',
    'Lesotho Loti': 'LSL',
    'Liberian Dollar': 'LRD',
    'Libyan Dinar': 'LYD',
    'Macanese Pataca': 'MOP',
    'Macedonian Denar': 'MKD',
    'Malagasy Ariary': 'MGA',
    'Malawian Kwacha': 'MWK',
    'Malaysian Ringgit': 'MYR',
    'Maldivian Rufiyaa': 'MVR',
    'Manx Pound': 'IMP',
    'Mauritanian Ouguiya': 'MRU',
    'Mauritian Rupee': 'MUR',
    'Mexican Peso': 'MXN',
    'Moldovan Leu': 'MDL',
    'Mongolian Tögrög': 'MNT',
    'Moroccan Dirham': 'MAD',
    'Mozambican Metical': 'MZN',
    'Namibian Dollar': 'NAD',
    'Nepalese Rupee': 'NPR',
    'Netherlands Antillian Guilder': 'ANG',
    'New Taiwan Dollar': 'TWD',
    'New Zealand Dollar': 'NZD',
    'Nicaraguan Córdoba': 'NIO',
    'Nigerian Naira': 'NGN',
    'Norwegian Krone': 'NOK',
    'Omani Rial': 'OMR',
    'Pakistani Rupee': 'PKR',
    'Panamanian Balboa': 'PAB',
    'Papua New Guinean Kina': 'PGK',
    'Paraguayan Guaraní': 'PYG',
    'Peruvian Sol': 'PEN',
    'Philippine Peso': 'PHP',
    'Polish Złoty': 'PLN',
    'Pound Sterling': 'GBP',
    'Qatari Riyal': 'QAR',
    'Romanian Leu': 'RON',
    'Russian Ruble': 'RUB',
    'Rwandan Franc': 'RWF',
    'Saint Helena Pound': 'SHP',
    'Samoan Tālā': 'WST',
    'Saudi Riyal': 'SAR',
    'Serbian Dinar': 'RSD',
    'Seychellois Rupee': 'SCR',
    'Sierra Leonean Leone': 'SLL',
    'Singapore Dollar': 'SGD',
    'Solomon Islands Dollar': 'SBD',
    'Somali Shilling': 'SOS',
    'South African Rand': 'ZAR',
    'South Korean Won': 'KRW',
    'South Sudanese Pound': 'SSP',
    'Special Drawing Rights': 'XDR',
    'Sri Lanka Rupee': 'LKR',
    'Sudanese Pound': 'SDG',
    'Surinamese Dollar': 'SRD',
    'Swedish Krona': 'SEK',
    'Swiss Franc': 'CHF',
    'Syrian Pound': 'SYP',
    'São Tomé and Príncipe Dobra': 'STN',
    'Tajikistani Somoni': 'TJS',
    'Tanzanian Shilling': 'TZS',
    'Thai Baht': 'THB',
    'Tongan Paʻanga': 'TOP',
    'Trinidad and Tobago Dollar': 'TTD',
    'Tunisian Dinar': 'TND',
    'Turkish Lira': 'TRY',
    'Turkmenistan Manat': 'TMT',
    'Tuvaluan Dollar': 'TVD',
    'UAE Dirham': 'AED',
    'Ugandan Shilling': 'UGX',
    'Ukrainian Hryvnia': 'UAH',
    'United States Dollar': 'USD',
    'Uruguayan Peso': 'UYU',
    "Uzbekistani So'm": 'UZS',
    'Vanuatu Vatu': 'VUV',
    'Venezuelan Bolívar Soberano': 'VES',
    'Vietnamese Đồng': 'VND',
    'West African CFA franc': 'XOF',
    'Yemeni Rial': 'YER',
    'Zambian Kwacha': 'ZMW'
}  # Supported Codes - Reverse
URL = "https://v6.exchangerate-api.com/v6/"
CONVERSION_RATES = "conversion_rates"
CONVERSION_RATE = "conversion_rate"
CONVERSION_RESULTS = "conversion_result"
CONVERSION_AMOUNT = "conversion_amounts"
BASE_CODE = "base_code"
TARGET_CODE = "target_code"
RESULT = "result"
ERROR_TYPE = "error-type"
PLAN_QUOTA = "plan_quota"
REQUEST_REMAINING = "requests_remaining"
REFRESH_DAY_OF_MONTH = "refresh_day_of_month"
TARGET_DATA = "target_data"
LOCALE = "locale"
TWO_LETTER_CODE = "two_letter_code"
CURRENCY_NAME = "currency_name"
CURRENCY_NAME_SHORT = "currency_name_short"
CURRENCY_SYMBOL = "display_symbol"
FLAG_URL = "flag_url"
TIME_LAST_UPDATE_UNIX = "time_last_update_unix"
TIME_LAST_UPDATE_UTC = "time_last_update_utc"
TIME_NEXT_UPDATE_UNIX = "time_next_update_unix"
TIME_NEXT_UPDATE_UTC = "time_next_update_utc"
